### ISSUE TITLE
Single instance on vagrant instructions

### ISSUE THREAD

**Issue by dudleycarr** [seomoz/roger-mesos#2]
There are are a couple of issues with the instructions for starting a single node Mesos instance within Vagrant:
1. The README should use `setup-single-node.sh` instead of `sh provision_single_cluster.sh`
2. The process fails with updating the linux image. A `sudo apt-get update` is required before the roles can be executed.
3. The provision script does NOT prompt for the username, but just the `vagrant` password.

**Comment by ankanm** [comment]
On 2 I assume you had to do a `sudo apt-get update` after vagrant ssh. I don't see that issue. I'm wondering if it's because I've a newer image. Either way I'll add an update cache in the base role so that happens first.
