### ISSUE TITLE
Use Vagrant's built-in provisioning

### ISSUE THREAD

**Issue by dudleycarr** [seomoz/roger-mesos#4]
Vagrantfile has the ability to do execute provisioning steps after the instance has been stood up. Run the appropriate script. I would also personally suggest creating two directories, one `single_node` and another `three_node` with their own Vagrant file. That way you don't need to suggest that people uncomment lines in the Vagrant file to get a multi-cluster setup working.

**Comment by miroswan** [comment]
It does handle conditionals and environment variables as well. If you use those, I single file might suffice without constant changes.

**Comment by miroswan** [comment]
Also, the landrush plugin handles DNS pretty well. I believe most of these steps can be handled directly in the Vagrantfile.

**Comment by b4hand** [comment]
We have examples of using Vagrantfile to provision different instances. It does work, but it means you have to pass an additional argument to the normal `vagrant` commands like: `vagrant up box1` versus `vagrant up box2`.

**Comment by ankanm** [comment]
@dudleycarr - The ansible scripts need to be run from a control machine (could be your laptop or a server or anything that can run ansible). The vagrant VMs are just examples. But you could create an inventory file (just like the files in hosts dir) and then call the ansible playbooks as in the example scripts.
I like the single_node and three_node dir ideas. I'll split that out.

**Comment by dudleycarr** [comment]
@ankanm I'm not suggesting removing the Ansible scripts. I was just suggesting that if you go the Vagrant route, that it automatically provisions using Ansible within the Vagrantfile instead of having the user do it by hand after `vagrant up`

**Comment by miroswan** [comment]
@dudleycarr  I have some code that does this in one step here: https://github.com/seomoz/roger-mesos/tree/provisioning-update

I'll probably end up branching off of Ankan's latest PR and making some adjustments to support this if approved.

**Comment by ankanm** [comment]
Ok. That makes complete sense @dudleycarr. Sounds good @miroswan.
